name: black_vault
description: Interact with Black Vault
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  filesize: ^2.0.1
  universal_html: ^2.0.8
  custom_navigation_bar: ^0.8.2
  web3dart: ^2.3.2
  solana: ^0.13.3+1
  shared_preferences: ^2.0.8
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  crypto: ^3.0.1
  tinycolor: ^1.0.3
  path_provider: ^2.0.6
  encrypt: ^5.0.1
  simple_gradient_text: ^1.2.2
  flutter_gradient_colors: ^2.1.1
  provider: ^6.0.1
  gradient_ui_widgets: ^1.0.2-nullsafety
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true